[general]
connection = "Data Source=../data/ArmoredCore6.db"
output = "DatabaseTypes.fs"
namespace = "WikidotScraper.DatabaseTypes"
cli_mutable = true
[sqlhydra_query_integration]
provider_db_type_attributes = true
table_declarations = true
[readers]
reader_type = "System.Data.Common.DbDataReader"
[filters]
include = []
exclude = []
